# frozen_string_literal: true

module Engine
  class GameError < RuntimeError
  end

  # problem with creating the Engine::Action object
  class ActionError < GameError
  end

  # errors generated by route.revenue and used by auto_router

  class NoToken < GameError
  end

  class RouteTooShort < GameError
  end

  class RouteTooLong < GameError
  end

  class ReusesCity < GameError
  end
end
